(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const API='https://jkmrjeplpsfpciveycia.supabase.co/functions/v1/campus-knockout-api';
const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d'),wrap=$('#canvasWrap');
const OPP=[
{name:'The Procrastinator',tag:'Due date? Never heard of it.',shirt:'#7657d6',skin:'#d8a675',hair:'#24212b',hp:92,tempo:1850,damage:12,tell:780,intro:'I was gonna train for this... tomorrow.',between:'Hold on. I just need one more scroll.',special:'Doom Scroll',pattern:['jabL','jabR','yawn','hookL']},
{name:'Group Project Greg',tag:'Contributed one Google Doc comment.',shirt:'#2ba8a0',skin:'#ba805d',hair:'#3b291e',hp:110,tempo:1600,damage:14,tell:700,intro:'I put my name on the title slide. We good?',between:'Can somebody send me what we are presenting?',special:'Credit Steal',pattern:['jabR','hookL','credit','jabL','hookR']},
{name:'Parking Pat',tag:'Citation specialist. Mercy unavailable.',shirt:'#e38b2f',skin:'#efc08c',hair:'#55372a',hp:128,tempo:1450,damage:16,tell:650,intro:'Permit expired three minutes ago. Square up.',between:'That corner of the ring is a fire lane.',special:'Citation Slam',pattern:['hookR','ticket','jabL','jabR','ticket']},
{name:'Professor Final',tag:'Cumulative. Closed notes. No curve.',shirt:'#3f70be',skin:'#b87d59',hair:'#d4d4d4',hp:148,tempo:1280,damage:18,tell:590,intro:'Everything since week one is fair game.',between:'You should have read the syllabus.',special:'Pop Quiz Barrage',pattern:['quizL','quizR','hookL','quizR','jabL','hookR']},
{name:'Student Loan Steve',tag:'Interest compounds. So do his punches.',shirt:'#b43745',skin:'#d49c6f',hair:'#161616',hp:175,tempo:1120,damage:21,tell:520,intro:'Your grace period is over.',between:'That knockdown has been added to principal.',special:'Compound Interest',pattern:['jabL','interest','hookR','jabR','hookL','interest','jabL']}
];
const DIFF={freshman:{mult:.82,score:.85},junior:{mult:1,score:1},senior:{mult:1.18,score:1.25}};
let settings=JSON.parse(localStorage.getItem('ck_settings')||'null')||{sound:true,shake:true,motion:false};
let profile=loadProfile(),fight=null,raf=0,last=performance.now(),audioCtx=null,input={dodgeL:false,dodgeR:false,block:false};
function uuid(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}
function defaultProfile(){return{save_token:uuid(),nickname:'',current_opponent:0,opponents_defeated:0,total_score:0,wins:0,losses:0,difficulty:'junior',unlocks:[0],progress:{campaign_start:Date.now(),best_score:0}}}
function loadProfile(){try{return JSON.parse(localStorage.getItem('ck_save'))||defaultProfile()}catch{return defaultProfile()}}
function saveLocal(){localStorage.setItem('ck_save',JSON.stringify(profile));updateContinue()}
function cleanName(v){return String(v||'').trim().replace(/[^a-zA-Z0-9 _-]/g,'').replace(/\s+/g,' ').slice(0,18)}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id!=='fight')stopLoop()}
function updateContinue(){const b=$('#continueBtn');b.disabled=!profile.nickname;$('#saveStatus').textContent=profile.nickname?`Saved fighter: ${profile.nickname} • ${OPP[Math.min(profile.current_opponent,4)].name}`:'No saved fighter yet.'}
function saveSettings(){localStorage.setItem('ck_settings',JSON.stringify(settings));$('#soundSetting').checked=settings.sound;$('#shakeSetting').checked=settings.shake;$('#motionSetting').checked=settings.motion;$('#soundToggle').textContent=settings.sound?'🔊':'🔇'}
function beep(type='hit'){if(!settings.sound)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime;let f=150,d=.08,v=.05;if(type==='bell'){f=720;d=.35;v=.06}else if(type==='block'){f=90;d=.1}else if(type==='ko'){f=55;d=.5;v=.08}else if(type==='menu'){f=420;d=.05;v=.03}else if(type==='victory'){f=540;d=.45;v=.06}o.type=type==='bell'?'sine':'square';o.frequency.setValueAtTime(f,t);if(type==='victory')o.frequency.exponentialRampToValueAtTime(980,t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+d)}catch{}}
function shake(){if(settings.shake&&!settings.motion){wrap.classList.remove('shake');void wrap.offsetWidth;wrap.classList.add('shake')}}
async function api(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...payload})});if(!r.ok)throw new Error(await r.text());return r.json()}
async function cloudSave(){saveLocal();try{await api('save',{save:profile})}catch(e){console.warn('Cloud save unavailable',e)}}
async function cloudLoad(){try{const d=await api('load',{save_token:profile.save_token});if(d.save){profile=d.save;saveLocal();return true}}catch(e){console.warn('Cloud load unavailable',e)}return false}
async function submitScore(completed=false){const entry={save_token:profile.save_token,nickname:profile.nickname,score:profile.total_score,opponents_defeated:profile.opponents_defeated,highest_opponent:OPP[Math.min(profile.current_opponent,4)].name,completion_time_ms:completed?Date.now()-profile.progress.campaign_start:null,completed};try{await api('submit_score',{entry})}catch(e){console.warn('Leaderboard submit failed',e)}}
async function renderBoard(){show('leaderboard');$('#boardStatus').textContent='Loading online leaderboard…';let rows=[];try{rows=(await api('leaderboard')).entries||[];$('#boardStatus').textContent='Online leaderboard'}catch{$('#boardStatus').textContent='Leaderboard is temporarily unavailable.'}const body=$('#boardBody');body.innerHTML='';if(!rows.length){body.innerHTML='<tr><td colspan="6">No scores yet. Be the first.</td></tr>';return}rows.slice(0,10).forEach((r,i)=>{const tr=document.createElement('tr'),time=r.completion_time_ms?fmtTime(r.completion_time_ms):'—';tr.innerHTML=`<td>${i+1}</td><td></td><td>${Number(r.score||0).toLocaleString()}</td><td>${r.opponents_defeated||0}</td><td></td><td>${time}</td>`;tr.children[1].textContent=r.nickname||'Anonymous';tr.children[4].textContent=r.highest_opponent||'—';body.appendChild(tr)})}
function fmtTime(ms){const s=Math.floor(ms/1000),m=Math.floor(s/60);return`${m}:${String(s%60).padStart(2,'0')}`}
function newGame(){profile=defaultProfile();$('#nickname').value='';$('#difficulty').value='junior';$('#setupError').textContent='';show('setup')}
async function continueGame(){beep('menu');await cloudLoad();startFight(profile.current_opponent)}
function startFight(index){index=Math.max(0,Math.min(4,index));profile.current_opponent=index;saveLocal();const o=OPP[index],dm=DIFF[profile.difficulty].mult,now=performance.now();fight={index,round:1,maxRounds:index<2?2:3,roundTime:45,roundStarted:now,playerHP:100,playerMax:100,opHP:Math.round(o.hp*dm),opMax:Math.round(o.hp*dm),stamina:100,paused:false,ended:false,attackIndex:0,opPhase:'idle',phaseUntil:0,nextAttack:now+1300,attack:null,counterUntil:0,playerAnim:'idle',playerAnimUntil:0,opAnim:'idle',punches:0,hits:0,counters:0,dodges:0,blocks:0,knockdowns:0,roundWins:0,roundLosses:0,scoreEarned:0,message:o.intro,messageUntil:now+2200,lastAction:0};$('#pName').textContent=profile.nickname;$('#oName').textContent=o.name;$('#oTag').textContent=o.tag;show('fight');overlay(`ROUND 1<br><small>${o.intro}</small>`,1500);beep('bell');updateHud();startLoop()}
function overlay(html,ms=900){const el=$('#overlay');el.innerHTML=html;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),ms)}
function startLoop(){cancelAnimationFrame(raf);last=performance.now();const loop=t=>{const dt=Math.min(40,t-last);last=t;if(fight&&!fight.paused&&!fight.ended)update(t,dt);draw(t);if($('#fight').classList.contains('active'))raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop)}
function stopLoop(){cancelAnimationFrame(raf);raf=0}
function update(t,dt){const o=OPP[fight.index],dm=DIFF[profile.difficulty].mult;fight.stamina=Math.min(100,fight.stamina+dt*(input.block?.01:.024));if(input.block)fight.stamina=Math.max(0,fight.stamina-dt*.018);if(fight.stamina<=1)input.block=false;fight.roundTime=Math.max(0,45-(t-fight.roundStarted)/1000);if(fight.roundTime<=0){endRound();return}if(fight.opPhase==='idle'&&t>=fight.nextAttack)beginAttack(t);if(fight.opPhase==='telegraph'&&t>=fight.phaseUntil)resolveAttack(t);if(fight.opPhase==='recovery'&&t>=fight.phaseUntil){fight.opPhase='idle';fight.opAnim='idle';fight.nextAttack=t+o.tempo*(.75+Math.random()*.35)/dm}if(fight.playerAnim!=='idle'&&t>=fight.playerAnimUntil)fight.playerAnim='idle';updateHud()}
function beginAttack(t){const o=OPP[fight.index],code=o.pattern[fight.attackIndex++%o.pattern.length],map={jabL:['LEFT JAB','left','jab'],jabR:['RIGHT JAB','right','jab'],hookL:['LEFT HOOK','left','hook'],hookR:['RIGHT HOOK','right','hook'],yawn:['GIANT YAWN','special','yawn'],credit:['CREDIT STEAL','special','credit'],ticket:['CITATION SLAM','special','ticket'],quizL:['POP QUIZ: LEFT','left','quiz'],quizR:['POP QUIZ: RIGHT','right','quiz'],interest:['COMPOUND INTEREST','special','interest']},a=map[code];fight.attack={code,label:a[0],side:a[1],kind:a[2]};fight.opPhase='telegraph';fight.opAnim='windup';const special=['yawn','credit','ticket','interest'].includes(a[2]);fight.phaseUntil=t+o.tell*(special?1.35:1)/DIFF[profile.difficulty].mult;fight.message=a[0]+'!';fight.messageUntil=fight.phaseUntil+160}
function resolveAttack(t){const o=OPP[fight.index],a=fight.attack;fight.opAnim='punch';let avoided=false,blocked=false;const correct=a.side==='left'?'dodgeR':a.side==='right'?'dodgeL':null;if(a.kind==='yawn'){avoided=true;fight.counterUntil=t+1100;fight.message='HE IS YAWNING — COUNTER!';fight.messageUntil=t+900}else if(a.kind==='credit'){if(input.block&&fight.stamina>10)blocked=true;else if(input.dodgeL||input.dodgeR)avoided=true;else damagePlayer(Math.round(o.damage*1.25))}else if(a.kind==='ticket'){if(input.dodgeL||input.dodgeR)avoided=true;else if(input.block&&fight.stamina>14){blocked=true;fight.stamina-=14}else damagePlayer(Math.round(o.damage*1.35))}else if(a.kind==='interest'){if(input.dodgeL||input.dodgeR)avoided=true;else if(input.block&&fight.stamina>18){blocked=true;fight.stamina-=18}else damagePlayer(Math.round(o.damage*1.55))}else if(input[correct])avoided=true;else if(input.block&&fight.stamina>8){blocked=true;fight.stamina-=8}else damagePlayer(Math.round(o.damage*(a.kind==='hook'?1.18:1)));if(avoided){fight.dodges++;fight.counterUntil=t+(a.kind==='interest'?1000:720);fight.message='DODGED! COUNTER NOW!';fight.messageUntil=t+650;beep('menu')}if(blocked){fight.blocks++;fight.message='BLOCKED!';fight.messageUntil=t+350;beep('block')}fight.opPhase='recovery';fight.phaseUntil=t+(a.kind==='interest'?1050:a.kind==='yawn'?900:520)}
function damagePlayer(n){fight.playerHP=Math.max(0,fight.playerHP-n);fight.message=`-${n} HP`;fight.messageUntil=performance.now()+420;beep('hit');shake();if(fight.playerHP<=0)down(false)}
function punch(side){if(!fight||fight.paused||fight.ended)return;const t=performance.now();if(t-fight.lastAction<130)return;fight.lastAction=t;if(fight.stamina<12){fight.message='OUT OF STAMINA';fight.messageUntil=t+450;beep('block');return}fight.stamina-=12;fight.punches++;fight.playerAnim=side==='left'?'punchL':'punchR';fight.playerAnimUntil=t+180;let chance=.42,damage=5+Math.random()*3;const counter=t<=fight.counterUntil,vulnerable=fight.opPhase==='recovery'||counter;if(vulnerable)chance=.96;else if(fight.opPhase==='telegraph')chance=.72;if(Math.random()<chance){fight.hits++;if(counter){damage*=2.35;fight.counters++;fight.scoreEarned+=120;fight.message='PERFECT COUNTER!';fight.messageUntil=t+520}else{fight.message='HIT!';fight.messageUntil=t+240}if(fight.index===4&&fight.attack?.kind==='interest'&&counter)damage*=1.3;fight.opHP=Math.max(0,fight.opHP-Math.round(damage));fight.scoreEarned+=Math.round(damage*11);beep('hit');shake();if(fight.opHP<=0)down(true)}else{fight.message='WHIFF!';fight.messageUntil=t+220;beep('menu')}}
function dodge(dir){if(!fight||fight.paused||fight.ended)return;input.dodgeL=dir==='left';input.dodgeR=dir==='right';fight.playerAnim=dir==='left'?'dodgeL':'dodgeR';fight.playerAnimUntil=performance.now()+300;setTimeout(()=>{input.dodgeL=false;input.dodgeR=false},300)}
function setBlock(v){if(!fight||fight.paused||fight.ended)return;input.block=v&&fight.stamina>1;fight.playerAnim=input.block?'block':'idle'}
function down(playerWon){fight.ended=true;if(playerWon)fight.knockdowns++;beep('ko');overlay(playerWon?'DOWN!<br><small>1... 2... 3...</small>':'YOU ARE DOWN!<br><small>1... 2... 3...</small>',2200);setTimeout(()=>finishFight(playerWon,'KO'),2250)}
function endRound(){if(fight.ended)return;const p=fight.playerHP/fight.playerMax,o=fight.opHP/fight.opMax;if(p>=o)fight.roundWins++;else fight.roundLosses++;if(fight.round>=fight.maxRounds){finishFight(fight.roundWins>=fight.roundLosses,'DECISION');return}fight.round++;fight.roundStarted=performance.now();fight.playerHP=Math.min(100,fight.playerHP+22);fight.opHP=Math.min(fight.opMax,fight.opHP+Math.round(fight.opMax*.18));fight.stamina=100;fight.opPhase='idle';fight.nextAttack=performance.now()+1400;overlay(`ROUND ${fight.round}<br><small>${OPP[fight.index].between}</small>`,1800);beep('bell')}
async function finishFight(win,method){if(!fight)return;fight.ended=true;const acc=fight.punches?fight.hits/fight.punches:0,time=Math.max(1,(performance.now()-fight.roundStarted)/1000);let bonus=Math.round((acc*1200)+(fight.playerHP*8)+(fight.counters*180)+(fight.knockdowns*500)+Math.max(0,45-time)*12);bonus=Math.round((fight.scoreEarned+bonus)*DIFF[profile.difficulty].score);if(win){profile.wins++;profile.total_score+=bonus;profile.opponents_defeated=Math.max(profile.opponents_defeated,fight.index+1);profile.current_opponent=Math.min(4,fight.index+1);profile.unlocks=[...new Set([...profile.unlocks,profile.current_opponent])];beep('victory')}else{profile.losses++;profile.total_score=Math.max(0,profile.total_score-Math.round(250*DIFF[profile.difficulty].score))}profile.progress.best_score=Math.max(profile.progress.best_score||0,profile.total_score);await cloudSave();if(win)await submitScore(fight.index===4);renderResult(win,bonus,acc,method)}
function renderResult(win,bonus,acc,method){const o=OPP[fight.index];show('result');$('#resultEyebrow').textContent=win?(fight.index===4?'DEGREE EARNED':'VICTORY'):'ACADEMIC PROBATION';$('#resultTitle').textContent=win?(fight.index===4?'YOU SURVIVED COLLEGE!':`${o.name} DEFEATED!`):'YOU GOT SCHOOLED!';$('#resultQuote').textContent=win?(fight.index===4?'“Congratulations. Your balance is still due.” — Student Loan Steve':`“${o.between}” — ${o.name}`):`“${o.intro}” — ${o.name}`;$('#fightStats').innerHTML=`<div><b>${Math.round(acc*100)}%</b><small>Accuracy</small></div><div><b>${fight.counters}</b><small>Counters</small></div><div><b>${fight.dodges}</b><small>Dodges</small></div><div><b>${win?'+'+bonus:profile.total_score}</b><small>${win?'Fight Score':'Total Score'}</small></div>`;const c=$('#nextCard'),b=$('#nextBtn');if(win&&fight.index<4){c.innerHTML=`NEXT: <strong>${OPP[fight.index+1].name}</strong><br><small>${OPP[fight.index+1].tag}</small>`;b.textContent='NEXT FIGHT'}else if(win){c.innerHTML=`FINAL SCORE: <strong>${profile.total_score.toLocaleString()}</strong><br><small>Your score is on the online leaderboard.</small>`;b.textContent='VIEW LEADERBOARD'}else{c.innerHTML=`REMATCH: <strong>${o.name}</strong><br><small>Study the tells and try again.</small>`;b.textContent='REMATCH'}}
function updateHud(){if(!fight)return;$('#pHp').style.width=(fight.playerHP/fight.playerMax*100)+'%';$('#oHp').style.width=(fight.opHP/fight.opMax*100)+'%';$('#pStamina').style.width=fight.stamina+'%';$('#roundText').textContent=`ROUND ${fight.round}/${fight.maxRounds}`;$('#timerText').textContent=`0:${String(Math.ceil(fight.roundTime)).padStart(2,'0')}`;$('#scoreText').textContent=`SCORE ${(profile.total_score+fight.scoreEarned).toLocaleString()}`}
function draw(){if(!fight)return;const W=canvas.width,H=canvas.height,o=OPP[fight.index],g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#11182b');g.addColorStop(.55,'#28334a');g.addColorStop(.56,'#bd9161');g.addColorStop(1,'#77563b');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#080b12';for(let i=0;i<22;i++){const x=(i*47+23)%W,y=105+(i%3)*26;ctx.beginPath();ctx.arc(x,y,14,0,Math.PI*2);ctx.fill();ctx.fillStyle=i%4===0?'#f6c945':'#29344a';ctx.fillRect(x-5,y-6,10,8);ctx.fillStyle='#080b12'}for(const y of[250,300,350]){ctx.strokeStyle=y===300?'#e4e4df':'#c74444';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.strokeStyle='#f1f1e8';ctx.lineWidth=5;ctx.strokeRect(100,220,W-200,H-245);ctx.fillStyle='rgba(255,255,255,.08)';ctx.fillRect(104,354,W-208,H-133);drawOpponent(o);drawPlayer();if(performance.now()<=fight.counterUntil){ctx.strokeStyle='#f6c945';ctx.lineWidth=8;ctx.strokeRect(12,12,W-24,H-24);ctx.fillStyle='#f6c945';ctx.font='bold 24px monospace';ctx.textAlign='center';ctx.fillText('COUNTER WINDOW!',W/2,52)}if(performance.now()<=fight.messageUntil){ctx.font='bold 30px monospace';ctx.textAlign='center';ctx.fillStyle='#fff';ctx.strokeStyle='#000';ctx.lineWidth=7;ctx.strokeText(fight.message,W/2,190);ctx.fillText(fight.message,W/2,190)}}
function drawOpponent(o){let x=480,y=285,ox=0,oy=0,s=1;if(fight.opAnim==='windup'){ox=fight.attack?.side==='left'?-18:18;oy=-4;s=1.03}else if(fight.opAnim==='punch'){ox=fight.attack?.side==='left'?55:-55;oy=35;s=1.08}if(fight.opHP<=0){oy=145;s=.9}ctx.save();ctx.translate(x+ox,y+oy);ctx.scale(s,s);ctx.fillStyle='rgba(0,0,0,.25)';ctx.beginPath();ctx.ellipse(0,130,105,24,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=o.shirt;ctx.fillRect(-72,25,144,105);ctx.fillStyle=o.skin;ctx.beginPath();ctx.arc(0,-35,63,0,Math.PI*2);ctx.fill();ctx.fillStyle=o.hair;ctx.beginPath();ctx.arc(0,-63,61,Math.PI,0);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(-36,-45,20,10);ctx.fillRect(16,-45,20,10);ctx.fillStyle='#111';ctx.fillRect(-28,-43,6,6);ctx.fillRect(22,-43,6,6);ctx.fillStyle=o.skin;ctx.fillRect(-102,30,30,110);ctx.fillRect(72,30,30,110);ctx.fillStyle='#e3424c';ctx.beginPath();ctx.arc(-93,140,27,0,Math.PI*2);ctx.arc(93,140,27,0,Math.PI*2);ctx.fill();ctx.fillStyle='#eef1f5';ctx.font='bold 15px monospace';ctx.textAlign='center';ctx.fillText(String(fight.index+1).padStart(2,'0'),0,74);if(fight.attack?.kind==='ticket'&&fight.opPhase==='telegraph'){ctx.fillStyle='#fff0aa';ctx.fillRect(105,35,55,80);ctx.fillStyle='#222';ctx.font='12px monospace';ctx.fillText('TICKET',133,60)}if(fight.attack?.kind==='quiz'&&fight.opPhase==='telegraph'){ctx.fillStyle='#fff';ctx.fillRect(-30,-125,60,34);ctx.fillStyle='#111';ctx.font='bold 20px monospace';ctx.fillText('?',0,-101)}if(fight.attack?.kind==='interest'&&fight.opPhase==='telegraph'){ctx.fillStyle='#f6c945';ctx.font='bold 28px monospace';ctx.fillText('$ + %',0,-115)}ctx.restore()}
function drawPlayer(){let x=480,y=465,tilt=0;if(fight.playerAnim==='dodgeL'){x-=110;tilt=-.15}if(fight.playerAnim==='dodgeR'){x+=110;tilt=.15}ctx.save();ctx.translate(x,y);ctx.rotate(tilt);ctx.fillStyle='#245aa5';ctx.beginPath();ctx.arc(0,50,92,Math.PI,0);ctx.fill();ctx.fillStyle='#b97954';ctx.beginPath();ctx.arc(0,-5,47,0,Math.PI*2);ctx.fill();ctx.fillStyle='#25252b';ctx.beginPath();ctx.arc(0,-21,46,Math.PI,0);ctx.fill();let lx=-72,rx=72,ly=-5,ry=-5;if(fight.playerAnim==='punchL'){lx=-8;ly=-105}if(fight.playerAnim==='punchR'){rx=8;ry=-105}if(fight.playerAnim==='block'||input.block){lx=-30;rx=30;ly=ry=-70}ctx.fillStyle='#e7424c';ctx.beginPath();ctx.arc(lx,ly,34,0,Math.PI*2);ctx.arc(rx,ry,34,0,Math.PI*2);ctx.fill();ctx.restore()}
$('#newBtn').addEventListener('click',()=>{beep('menu');newGame()});$('#continueBtn').addEventListener('click',continueGame);$('#boardBtn').addEventListener('click',()=>{beep('menu');renderBoard()});$('#howBtn').addEventListener('click',()=>{beep('menu');show('how')});$('#settingsBtn').addEventListener('click',()=>{beep('menu');show('settings')});$$('.back').forEach(b=>b.addEventListener('click',()=>{beep('menu');show('menu');updateContinue()}));
$('#setupForm').addEventListener('submit',e=>{e.preventDefault();const name=cleanName($('#nickname').value);if(name.length<2){$('#setupError').textContent='Use at least 2 letters or numbers.';return}profile=defaultProfile();profile.nickname=name;profile.difficulty=$('#difficulty').value;profile.progress.campaign_start=Date.now();cloudSave();beep('bell');startFight(0)});
$('#pauseBtn').addEventListener('click',()=>{if(!fight)return;fight.paused=!fight.paused;$('#pauseBtn').textContent=fight.paused?'RESUME':'PAUSE';if(fight.paused)overlay('PAUSED',999999);else{$('#overlay').classList.add('hidden');fight.roundStarted=performance.now()-(45-fight.roundTime)*1000}});$('#restartBtn').addEventListener('click',()=>startFight(fight?.index||0));$('#quitBtn').addEventListener('click',()=>{show('menu');updateContinue()});$('#resultMenu').addEventListener('click',()=>{show('menu');updateContinue()});$('#nextBtn').addEventListener('click',()=>{if(fight.index===4&&profile.opponents_defeated>=5)renderBoard();else startFight(profile.current_opponent)});
$$('.controls button').forEach(b=>{const a=b.dataset.action,down=e=>{e.preventDefault();if(a==='punchL')punch('left');else if(a==='punchR')punch('right');else if(a==='dodgeL')dodge('left');else if(a==='dodgeR')dodge('right');else setBlock(true)},up=e=>{if(a==='block'){e.preventDefault();setBlock(false)}};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up)});
window.addEventListener('keydown',e=>{if(!$('#fight').classList.contains('active')||e.repeat)return;const k=e.key.toLowerCase();if(['a','d','s','p','arrowleft','arrowright'].includes(k))e.preventDefault();if(k==='a')punch('left');if(k==='d')punch('right');if(k==='arrowleft')dodge('left');if(k==='arrowright')dodge('right');if(k==='s')setBlock(true);if(k==='p')$('#pauseBtn').click()});window.addEventListener('keyup',e=>{if(e.key.toLowerCase()==='s')setBlock(false)});
$('#soundToggle').addEventListener('click',()=>{settings.sound=!settings.sound;saveSettings();if(settings.sound)beep('menu')});$('#soundSetting').addEventListener('change',e=>{settings.sound=e.target.checked;saveSettings()});$('#shakeSetting').addEventListener('change',e=>{settings.shake=e.target.checked;saveSettings()});$('#motionSetting').addEventListener('change',e=>{settings.motion=e.target.checked;saveSettings()});
saveSettings();updateContinue();updateHud();
})();
