(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const SUPABASE_URL='https://jkmrjeplpsfpciveycia.supabase.co';
const SUPABASE_KEY='sb_publishable_go8Ns2OeneQvMn5tT-8iBw_BPFVZMPD';
const MAX_PLAYERS=2;
const ROUND_SECONDS=45;
const MAX_ROUNDS=3;
const state={
  clientId:(crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now().toString(36)),
  room:'',role:'',nickname:'',ready:false,channel:null,players:[],match:null,sendTimer:0,raf:0,lastFrame:0,audio:null,seq:0
};
const sb=window.supabase?.createClient?.(SUPABASE_URL,SUPABASE_KEY,{realtime:{params:{eventsPerSecond:20}}});
const canvas=$('#onlineCanvas'),ctx=canvas?.getContext('2d');
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id)?.classList.add('active')}
function cleanName(v){return String(v||'').trim().replace(/[^a-zA-Z0-9 _-]/g,'').replace(/\s+/g,' ').slice(0,18)}
function makeCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<6;i++)s+=chars[Math.floor(Math.random()*chars.length)];return s}
function savedNickname(){try{return cleanName(JSON.parse(localStorage.getItem('ck_save')||'{}').nickname)||''}catch{return''}}
function setStatus(text,bad=false){const el=$('#onlineStatus');if(el){el.textContent=text;el.classList.toggle('error',bad)}}
function beep(kind='tap'){try{const cfg=JSON.parse(localStorage.getItem('ck_settings')||'{}');if(cfg.sound===false)return;state.audio=state.audio||new(window.AudioContext||window.webkitAudioContext)();const o=state.audio.createOscillator(),g=state.audio.createGain(),t=state.audio.currentTime;let f=330,d=.07;if(kind==='bell'){f=760;d=.3}else if(kind==='hit'){f=120;d=.08}else if(kind==='block'){f=80;d=.1}else if(kind==='win'){f=520;d=.45}else if(kind==='ko'){f=55;d=.45}o.type=kind==='bell'?'sine':'square';o.frequency.setValueAtTime(f,t);if(kind==='win')o.frequency.exponentialRampToValueAtTime(980,t+d);g.gain.setValueAtTime(.045,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(state.audio.destination);o.start();o.stop(t+d)}catch{}}
function mePresence(){return{id:state.clientId,nickname:state.nickname,role:state.role,ready:state.ready,online_at:new Date().toISOString()}}
function flattenPresence(){if(!state.channel)return[];const p=state.channel.presenceState();return Object.values(p).flat().filter(Boolean)}
function syncLobby(){state.players=flattenPresence();const unique=new Map();for(const p of state.players)if(p.id&&!unique.has(p.id))unique.set(p.id,p);state.players=[...unique.values()].sort((a,b)=>(a.role==='host'?-1:1)-(b.role==='host'?-1:1)||String(a.online_at||'').localeCompare(String(b.online_at||''))).slice(0,4);renderLobby();if(state.players.length>MAX_PLAYERS&&!state.players.slice(0,MAX_PLAYERS).some(p=>p.id===state.clientId)){leaveRoom(true).then(()=>{show('onlineSetup');setStatus('That room is full.',true)});return}if(state.match&&state.players.length<2&&!state.match.ended){finishOnline(state.clientId,'Opponent disconnected')}}
function renderLobby(){const list=$('#onlinePlayers');if(!list)return;list.innerHTML='';if(!state.players.length){list.innerHTML='<div class="onlinePlayer muted">Waiting for players…</div>';return}for(const p of state.players.slice(0,MAX_PLAYERS)){const row=document.createElement('div');row.className='onlinePlayer';const left=document.createElement('div');left.innerHTML=`<b></b><small>${p.role==='host'?'HOST':'CHALLENGER'}</small>`;left.querySelector('b').textContent=p.nickname||'Fighter';const badge=document.createElement('span');badge.className='readyBadge '+(p.ready?'isReady':'');badge.textContent=p.ready?'READY':'NOT READY';row.append(left,badge);list.append(row)}const start=$('#onlineStartBtn');if(start){const both=state.players.length===2&&state.players.every(p=>p.ready);start.hidden=state.role!=='host';start.disabled=!both}const ready=$('#onlineReadyBtn');if(ready){ready.textContent=state.ready?'NOT READY':'READY UP';ready.classList.toggle('primary',!state.ready);ready.classList.toggle('secondary',state.ready)}$('#roomCodeText').textContent=state.room||'------';const hint=$('#lobbyHint');if(hint)hint.textContent=state.role==='host'?'When both fighters are ready, start the match.':'Ready up and wait for the host to start.'}
async function joinChannel(room,role){if(!sb){setStatus('Online service failed to load. Refresh and try again.',true);return false}await leaveRoom(true);state.room=room.toUpperCase();state.role=role;state.ready=false;state.players=[];state.channel=sb.channel(`campus-knockout:${state.room}`,{config:{broadcast:{self:false,ack:false},presence:{key:state.clientId}}});state.channel
.on('presence',{event:'sync'},syncLobby)
.on('presence',{event:'join'},syncLobby)
.on('presence',{event:'leave'},syncLobby)
.on('broadcast',{event:'game'},({payload})=>onMessage(payload))
.subscribe(async status=>{if(status==='SUBSCRIBED'){await state.channel.track(mePresence());syncLobby()}else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'){setStatus('Could not connect to the online room.',true)}});show('onlineLobby');renderLobby();return true}
async function leaveRoom(silent=false){stopMatchLoop();if(state.channel){try{await state.channel.untrack()}catch{}try{await sb?.removeChannel(state.channel)}catch{}}state.channel=null;state.room='';state.role='';state.ready=false;state.players=[];state.match=null;if(!silent)show('menu')}
function send(payload){if(!state.channel)return;state.channel.send({type:'broadcast',event:'game',payload:{...payload,room:state.room,from:state.clientId}})}
function onlineOpen(){const n=savedNickname();$('#onlineNickname').value=n;$('#onlineJoinCode').value='';setStatus('Create a room or enter a friend’s room code.');show('onlineSetup')}
async function createRoom(){const n=cleanName($('#onlineNickname').value);if(n.length<2){setStatus('Enter a nickname with at least 2 characters.',true);return}state.nickname=n;setStatus('Creating room…');await joinChannel(makeCode(),'host')}
async function joinRoom(){const n=cleanName($('#onlineNickname').value),code=String($('#onlineJoinCode').value||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);if(n.length<2){setStatus('Enter a nickname with at least 2 characters.',true);return}if(code.length!==6){setStatus('Enter the 6-character room code.',true);return}state.nickname=n;setStatus('Joining room…');await joinChannel(code,'guest');setTimeout(async()=>{if(state.channel&&state.role==='guest'&&!state.players.some(p=>p.role==='host')){await leaveRoom(true);show('onlineSetup');setStatus('No host found in that room. Check the code and try again.',true)}},2400)}
async function toggleReady(){if(!state.channel)return;state.ready=!state.ready;await state.channel.track(mePresence());renderLobby();send({type:'presence_nudge'})}
function startByHost(){if(state.role!=='host'||state.players.length!==2||!state.players.every(p=>p.ready))return;const startAt=Date.now()+2600,matchId=Math.random().toString(36).slice(2,10);send({type:'start',startAt,matchId,round:1,scores:{host:0,guest:0}});beginMatch({startAt,matchId,round:1,scores:{host:0,guest:0}})}
function newFighter(){return{hp:100,stamina:100,blocking:false,dodgeUntil:0,dodgeDir:'',counterUntil:0,anim:'idle',animUntil:0,totalDamage:0,punches:0,hits:0,dodges:0,blocks:0}}
function beginMatch(msg){const opponent=state.players.find(p=>p.id!==state.clientId)||{id:'remote',nickname:'Opponent',role:state.role==='host'?'guest':'host'};state.match={id:msg.matchId,round:msg.round||1,scores:msg.scores||{host:0,guest:0},startAt:msg.startAt,roundEndsAt:msg.startAt+ROUND_SECONDS*1000,me:newFighter(),remote:newFighter(),remoteId:opponent.id,remoteName:opponent.nickname||'Opponent',ended:false,message:'',messageUntil:0,lastSend:0,processed:new Set(),countdown:true};$('#onlinePName').textContent=state.nickname;$('#onlineOName').textContent=state.match.remoteName;show('onlineFight');beep('bell');startMatchLoop()}
function onMessage(m){if(!m||m.from===state.clientId)return;if(m.type==='presence_nudge'){syncLobby();return}if(m.type==='start'){beginMatch(m);return}if(!state.match||m.matchId&&m.matchId!==state.match.id)return;if(m.type==='state'){Object.assign(state.match.remote,m.state||{});state.match.remoteName=m.nickname||state.match.remoteName;if(m.state?.anim&&m.state.anim!=='idle')state.match.remote.animUntil=performance.now()+220;$('#onlineOName').textContent=state.match.remoteName;return}if(m.type==='punch'){receivePunch(m);return}if(m.type==='hit_result'){if(m.target===state.clientId||m.attacker!==state.clientId)return;const now=performance.now();if(m.dodged){state.match.message='YOUR PUNCH MISSED';state.match.messageUntil=now+350}else if(m.blocked){state.match.me.totalDamage+=m.damage;state.match.message=`BLOCKED • ${m.damage} DAMAGE`;state.match.messageUntil=now+420}else{state.match.me.hits++;state.match.me.totalDamage+=m.damage;state.match.message=m.counter?'COUNTER CONNECTS!':'CLEAN HIT!';state.match.messageUntil=now+420}return}if(m.type==='ko'){finishOnline(m.winner,'KO');return}if(m.type==='round_end'){applyRoundEnd(m);return}if(m.type==='match_end'){finishOnline(m.winner,m.reason||'Decision');return}}
function receivePunch(m){if(state.match.ended)return;const key=`${m.from}:${m.seq}`;if(state.match.processed.has(key))return;state.match.processed.add(key);const me=state.match.me,now=performance.now();let dodged=now<me.dodgeUntil,blocked=false,damage=0;if(dodged){me.dodges++;me.counterUntil=now+760;state.match.message='DODGED! COUNTER NOW!';state.match.messageUntil=now+650;beep('tap')}else if(me.blocking&&me.stamina>5){blocked=true;me.blocks++;damage=m.counter?5:3;me.stamina=Math.max(0,me.stamina-7);beep('block')}else{damage=m.counter?17:(m.side==='right'?11:9);me.hp=Math.max(0,me.hp-damage);beep('hit');if(me.hp>0)flashCanvas()}send({type:'hit_result',matchId:state.match.id,attacker:m.from,target:state.clientId,seq:m.seq,damage,dodged,blocked,counter:!!m.counter});sendState(true);if(me.hp<=0){send({type:'ko',matchId:state.match.id,winner:m.from,loser:state.clientId});finishOnline(m.from,'KO')}}
function punch(side){const f=state.match?.me;if(!f||state.match.ended||Date.now()<state.match.startAt)return;const now=performance.now();if(f.anim!=='idle'&&now<f.animUntil)return;if(f.stamina<12){state.match.message='OUT OF STAMINA';state.match.messageUntil=now+450;return}f.stamina-=12;f.punches++;f.anim=side==='left'?'punchL':'punchR';f.animUntil=now+190;const counter=now<f.counterUntil;send({type:'punch',matchId:state.match.id,seq:++state.seq,side,counter,sentAt:Date.now()});sendState(true)}
function dodge(dir){const f=state.match?.me;if(!f||state.match.ended||Date.now()<state.match.startAt)return;const now=performance.now();if(f.stamina<8)return;f.stamina-=8;f.dodgeUntil=now+330;f.dodgeDir=dir;f.anim=dir==='left'?'dodgeL':'dodgeR';f.animUntil=now+330;sendState(true)}
function block(v){const f=state.match?.me;if(!f||state.match.ended||Date.now()<state.match.startAt)return;f.blocking=v&&f.stamina>0;f.anim=f.blocking?'block':'idle';sendState(true)}
function sendState(force=false){if(!state.match||state.match.ended)return;const now=performance.now();if(!force&&now-state.match.lastSend<90)return;state.match.lastSend=now;const f=state.match.me;send({type:'state',matchId:state.match.id,nickname:state.nickname,state:{hp:Math.round(f.hp*10)/10,stamina:Math.round(f.stamina*10)/10,blocking:f.blocking,dodgeUntil:f.dodgeUntil,dodgeDir:f.dodgeDir,anim:f.anim,animUntil:f.animUntil,totalDamage:f.totalDamage}})}
function tick(t,dt){const m=state.match;if(!m||m.ended)return;const f=m.me;if(Date.now()>=m.startAt){m.countdown=false;f.stamina=Math.min(100,f.stamina+dt*(f.blocking?.006:.022));if(f.blocking){f.stamina=Math.max(0,f.stamina-dt*.013);if(f.stamina<=1)f.blocking=false}if(f.anim!=='idle'&&t>=f.animUntil)f.anim=f.blocking?'block':'idle';sendState();if(state.role==='host'&&Date.now()>=m.roundEndsAt)hostEndRound()}updateOnlineHud()}
function hostEndRound(){const m=state.match;if(!m||m.ended||m._ending)return;m._ending=true;const hostId=state.clientId,guestId=m.remoteId;let winner=null;if(m.me.hp>m.remote.hp+1)winner=hostId;else if(m.remote.hp>m.me.hp+1)winner=guestId;const scores={...m.scores};if(winner===hostId)scores.host++;if(winner===guestId)scores.guest++;if(m.round>=MAX_ROUNDS){let finalWinner=scores.host>scores.guest?hostId:scores.guest>scores.host?guestId:null;if(!finalWinner){if(m.me.totalDamage>m.remote.totalDamage)finalWinner=hostId;else if(m.remote.totalDamage>m.me.totalDamage)finalWinner=guestId}send({type:'match_end',matchId:m.id,winner:finalWinner,reason:finalWinner?'Decision':'Draw'});finishOnline(finalWinner,finalWinner?'Decision':'Draw');return}const nextRound=m.round+1,startAt=Date.now()+2400;send({type:'round_end',matchId:m.id,winner,scores,nextRound,startAt});applyRoundEnd({winner,scores,nextRound,startAt})}
function applyRoundEnd(m){const match=state.match;if(!match||match.ended)return;match.round=m.nextRound;match.scores=m.scores;match.startAt=m.startAt;match.roundEndsAt=m.startAt+ROUND_SECONDS*1000;const myDamage=match.me.totalDamage,remoteDamage=match.remote.totalDamage;match.me=newFighter();match.remote=newFighter();match.me.totalDamage=myDamage;match.remote.totalDamage=remoteDamage;match._ending=false;match.message=`ROUND ${match.round}`;match.messageUntil=performance.now()+1600;overlayOnline(`ROUND ${match.round}`,1800);beep('bell');sendState(true)}
function finishOnline(winner,reason){const m=state.match;if(!m||m.ended)return;m.ended=true;stopMatchLoop();const draw=!winner,won=winner===state.clientId;const rec=JSON.parse(localStorage.getItem('ck_online_record')||'{"wins":0,"losses":0,"draws":0}');if(draw)rec.draws=(rec.draws||0)+1;else if(won)rec.wins=(rec.wins||0)+1;else rec.losses=(rec.losses||0)+1;localStorage.setItem('ck_online_record',JSON.stringify(rec));state.ready=false;try{state.channel?.track(mePresence())}catch{}$('#onlineResultEyebrow').textContent=draw?'DRAW':won?'ONLINE VICTORY':'ONLINE DEFEAT';$('#onlineResultTitle').textContent=draw?'NO DECISION':won?'YOU WON THE FIGHT!':'YOUR OPPONENT WON';$('#onlineResultReason').textContent=reason;$('#onlineRecord').textContent=`Online record on this device: ${rec.wins||0}-${rec.losses||0}-${rec.draws||0}`;show('onlineResult');beep(won?'win':'ko')}
function updateOnlineHud(){const m=state.match;if(!m)return;$('#onlinePHp').style.width=Math.max(0,m.me.hp)+'%';$('#onlineOHp').style.width=Math.max(0,m.remote.hp)+'%';$('#onlinePStamina').style.width=Math.max(0,m.me.stamina)+'%';$('#onlineRoundText').textContent=`ROUND ${m.round}/${MAX_ROUNDS}`;const remain=Math.max(0,Math.ceil((m.roundEndsAt-Date.now())/1000));$('#onlineTimerText').textContent=`0:${String(remain).padStart(2,'0')}`;$('#onlineScoreText').textContent=`${m.scores.host||0} - ${m.scores.guest||0}`}
function overlayOnline(text,ms=900){const e=$('#onlineOverlay');if(!e)return;e.innerHTML=text;e.classList.remove('hidden');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.add('hidden'),ms)}
function startMatchLoop(){stopMatchLoop();state.lastFrame=performance.now();const loop=t=>{const dt=Math.min(40,t-state.lastFrame);state.lastFrame=t;tick(t,dt);drawOnline(t);if(state.match&&!state.match.ended&&$('#onlineFight').classList.contains('active'))state.raf=requestAnimationFrame(loop)};state.raf=requestAnimationFrame(loop)}
function stopMatchLoop(){cancelAnimationFrame(state.raf);state.raf=0}
function flashCanvas(){const w=$('#onlineCanvasWrap');if(!w)return;w.classList.remove('onlineHit');void w.offsetWidth;w.classList.add('onlineHit')}
function drawOnline(t){if(!ctx||!state.match)return;const W=canvas.width,H=canvas.height,m=state.match;const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#11182b');g.addColorStop(.55,'#2c3550');g.addColorStop(.56,'#b98a5a');g.addColorStop(1,'#6f4c34');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#0a0d14';for(let i=0;i<24;i++){const x=(i*43+19)%W,y=105+(i%3)*25;ctx.beginPath();ctx.arc(x,y,13,0,Math.PI*2);ctx.fill();ctx.fillStyle=i%5===0?'#f6c945':'#34405b';ctx.fillRect(x-5,y-5,10,8);ctx.fillStyle='#0a0d14'}for(const y of[248,300,352]){ctx.strokeStyle=y===300?'#e14a4a':'#e9e8df';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.strokeStyle='#f1f1e8';ctx.lineWidth=5;ctx.strokeRect(100,220,W-200,H-245);drawRemote(m.remote,t);drawMe(m.me,t);const now=performance.now();if(now<m.messageUntil){ctx.font='bold 30px monospace';ctx.textAlign='center';ctx.strokeStyle='#000';ctx.lineWidth=7;ctx.fillStyle='#fff';ctx.strokeText(m.message,W/2,188);ctx.fillText(m.message,W/2,188)}if(Date.now()<m.startAt){const n=Math.ceil((m.startAt-Date.now())/1000);ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(0,0,W,H);ctx.font='bold 96px monospace';ctx.textAlign='center';ctx.fillStyle='#f6c945';ctx.fillText(n>0?n:'FIGHT!',W/2,H/2)}}
function boxer(ctx,x,y,facing,color,name,local,f,t){let dx=0;if(f.anim==='dodgeL')dx=local?-70:70;if(f.anim==='dodgeR')dx=local?70:-70;ctx.save();ctx.translate(x+dx,y);if(!local)ctx.scale(-1,1);ctx.fillStyle='rgba(0,0,0,.25)';ctx.beginPath();ctx.ellipse(0,105,75,20,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=color;ctx.fillRect(-48,10,96,92);ctx.fillStyle='#c98e67';ctx.beginPath();ctx.arc(0,-35,45,0,Math.PI*2);ctx.fill();ctx.fillStyle='#24222a';ctx.beginPath();ctx.arc(0,-55,44,Math.PI,0);ctx.fill();let lx=-62,rx=62,ly=25,ry=25;if(f.anim==='block'||f.blocking){lx=-25;rx=25;ly=ry=-25}else if(f.anim==='punchL'){lx=5;ly=-72}else if(f.anim==='punchR'){rx=5;ry=-72}ctx.fillStyle='#e74650';ctx.beginPath();ctx.arc(lx,ly,25,0,Math.PI*2);ctx.arc(rx,ry,25,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 14px monospace';ctx.textAlign='center';ctx.fillText(name.slice(0,14),0,70);ctx.restore()}
function drawMe(f,t){boxer(ctx,330,405,1,'#245aa5',state.nickname,true,f,t)}
function drawRemote(f,t){boxer(ctx,630,285,-1,'#a53949',state.match.remoteName,false,f,t)}
function backToLobby(){if(!state.channel){show('menu');return}state.ready=false;state.channel.track(mePresence());state.match=null;show('onlineLobby');syncLobby()}
$('#onlineBtn')?.addEventListener('click',onlineOpen);
$('#onlineBackBtn')?.addEventListener('click',()=>show('menu'));
$('#createOnlineBtn')?.addEventListener('click',createRoom);
$('#joinOnlineBtn')?.addEventListener('click',joinRoom);
$('#onlineReadyBtn')?.addEventListener('click',toggleReady);
$('#onlineStartBtn')?.addEventListener('click',startByHost);
$('#onlineLeaveBtn')?.addEventListener('click',()=>leaveRoom(false));
$('#onlineFightLeave')?.addEventListener('click',()=>{if(confirm('Leave this online fight?'))leaveRoom(false)});
$('#onlineRematchBtn')?.addEventListener('click',backToLobby);
$('#onlineResultMenu')?.addEventListener('click',()=>leaveRoom(false));
$$('[data-online-action]').forEach(b=>{const a=b.dataset.onlineAction;const down=e=>{e.preventDefault();if(a==='punchL')punch('left');else if(a==='punchR')punch('right');else if(a==='dodgeL')dodge('left');else if(a==='dodgeR')dodge('right');else if(a==='block')block(true)};const up=e=>{if(a==='block'){e.preventDefault();block(false)}};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up)});
window.addEventListener('keydown',e=>{if(!$('#onlineFight')?.classList.contains('active')||e.repeat)return;if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if(['a','d','s','arrowleft','arrowright'].includes(k))e.preventDefault();if(k==='a')punch('left');if(k==='d')punch('right');if(k==='arrowleft')dodge('left');if(k==='arrowright')dodge('right');if(k==='s')block(true)});
window.addEventListener('keyup',e=>{if(e.key.toLowerCase()==='s'&&$('#onlineFight')?.classList.contains('active'))block(false)});
window.addEventListener('beforeunload',()=>{try{state.channel?.untrack()}catch{}});
if($('#onlineNickname'))$('#onlineNickname').value=savedNickname();
})();
